### PR TITLE
Full support for Campaigns API

### PR DESCRIPTION
**Pull request by rue-kcarlton**
[Documentation](https://apidocs.klaviyo.com/reference/campaigns)

### CODE REVIEW

**Review by rgg-amahajan — APPROVED** [review]
looks great!

**Comment by cpcurtis1218** [comment]
Hey @rue-kcarlton would you please update the README in this PR to show example events?

**Comment by rue-kcarlton** [comment]
> Hey @rue-kcarlton would you please update the README in this PR to show example events?

Hi @cpcurtis1218- do you mean example calls to the Campaigns API via these changes or an example of when the PUT/POST failed because of how the data was attached to the query params instead of being in the body?

**Comment by cpcurtis1218** [comment]
Yes the example calls to the Campaigns API for these changes

**Review by shaileshbonzer — APPROVED** [review]
This functionality look correct, please merge it so others also able to use it.

**Comment by Ian-Montgomery-Klaviyo** [comment]
there is a newer node sdk with full support for the new campaigns api [here](https://github.com/klaviyo/klaviyo-api-node)

**Pull request closed without merging**
